name: API Tests

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 1. Устанавливаем Allure (вручную, чтобы не зависеть от докера)
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      # 2. Устанавливаем библиотеки Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Запускаем тесты
      - name: Run API Tests
        run: pytest tests/ --alluredir=allure-results
        continue-on-error: true

      # 4. Скачиваем историю прошлых тестов (для графиков трендов)
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 5. Генерируем отчет
      - name: Generate Allure Report
        if: always()
        run: |
          # Копируем историю
          if [ -d "gh-pages/history" ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi
          
          # Создаем HTML
          allure generate allure-results --clean -o allure-report

      # 6. Публикуем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
